<?php
////////////////////////////////////////////////////
/**
* The following PHP scripts displays all data of a staff member
*
* Code generated by Yjang Wynter (Web Developer)
* Florida Space Institute (Remote)
* University of Central Florida
*
* @author     Yjang Wynter <yjang.wynter@ucf.edu>
* @version    0.1
* 
*/
///////////////////////////////////////////////////////
$servername = "localhost"; // DB Server Host
$username  = "root"; //DB User
$password  = ""; // DB Password
$database  =  "fsi"; //Database name
$table = "science_staff";
$conn = new mysqli($servername, $username, $password,$database); // SQL Database Connector
//PDO

if (!$conn) {
  die('No pudo conectarse: ' . $conn->error($e)); // Failed to Connect
  }
  
  $sql = "INSERT INTO $table (FULL_NAME, PHONE_EXT, PRIMARY_MAIL, ALT_MAIL, POSITION, DEPARTMENT,  BIOGRAPHY, PROJECTS, RESEARCH_AREAS, RESEARCH_DESCRIPTION, MENTORING, PUBLICATIONS, ORCID_LINK) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
  $stmt =$conn->prepare($sql);
  $stmt ->bind_param("sssssssssssss",$name,$phone,$p_mail,$alt_mail,$pos,$dept, $bio,$projects,$res_areas,$res_desc, $mentoring,$pubs,$orcid_link);
  
//Test
$name ="Dylan Christian Hickson";
$phone ="319";
$p_mail ="dylan.hickson@ucf.edu";
$alt_mail="dy728893@ucf.edu";
$pos = "Postdoctoral Research Scientist";
$dept ="Planetary Sciences";
$bio = "Dylan Hickson is a Postdoctoral Research Scientist in the Planetary Science Group at the Arecibo Observatory, joining the Arecibo staff in May 2019 after receiving his Ph.D. in Earth and Space Science from York University in Toronto, Canada and Bachelor’s degrees in Earth and Environmental Science and Physical Science from McMaster University in Hamilton, Canada. In his undergraduate studies, Dylan focused on remote sensing and geophysics, specifically ground-penetrating radar, and contributed research on these topics within the Environmental and Archaeological Geophysics Laboratory at McMaster University, as well as for the Ontario Ministry of Agriculture, Food, and Rural Affairs. Dylan's Ph.D. dissertation focused on using laboratory experiments performed on various geologic materials to better interpret radar observations of asteroids. Now at Arecibo Observatory, Dylan is honored to join the dedicated staff in furthering planetary science, and honored as well to join the Puerto Rican community. In addition to radar remote sensing, Dylan is interested in the implementation and science return of space missions, participating on the science teams for the 2015 CanMars and AMADEE-18 Martian Analog Missions. His research interests include radar observations, regolith evolution on airless bodies, and modeling the surface/regolith properties, structures, and compositions of asteroids and other rocky solar system bodies. In his free time, Dylan enjoys playing music, reading, exploring nature, and spending time with his wonderful wife and all of their animals.";
$res_areas ="Planetary Radar; Asteroids and Comets; Planetary Surfaces; Space Weathering; Solar System Composition";
$res_desc ="Utilize radar polarimetry and radar scattering theory to analyze radar data of rocky and icy bodies in the solar system, inverting these data for near-surface properties such as roughness, texture, structure, and composition. - Model the electromagnetic properties of geologic materials with validation by laboratory experimentation for improved remote sensing interpretations.- Combine radar with multi-wavelength observations in the UV, VIS, and IR to develop coherent analyses of remote sensing data.";
$projects= "Dylan Hickson is fully supported by NASA’s Near-Earth Object Observations Program through grants no. 80NSSC18K1098 and no. 80NSSC19K0523 awarded to the University of Central Florida (UCF), and through UCF's Preeminent Postdoctoral Program";
$mentoring ="";
$pubs = "
Peer-Reviewed publications

Hickson, D.C., Boivin, A.L., Tsai, C.-A., Daly, M.G., and Ghent, R.R. (2019) Modeling the Dielectric Properties of Minerals from Crystals to Bulk Powders for Improved Interpretation of Asteroid Radar Observations. Submitted to Journal of Geophysical Research: Planets. 

Lalla, E., Cote, K., Hickson, D., Garnitschnig, S., Konstantinidis, M., Such, P., Czakler, C., Schroder, C., Frigeri, A., Ercoli, M., Losiak, A., Gruber, S., and Groemer, G. (2019) Laboratory analysis of returned samples from the AMADEE-18 Mars analog mission. Astrobiology, In-press. 

Boivin, A.L., Tsai, C.-A., Hickson, D.C., Ghent, R.R., and Daly, M.G. (2019) MCMC-based Two-Port Transmission Line Permittivity and Permeability Determination. Submitted to IEEE Trans. Microw. Theory Techn. 

Tsai, C., Ghent, R., Boivin, A., and Hickson, D. (2019) Discrimination of Dispersive Materials From Q* Radar Signals Using Q*. Ground Penetrating Radar, 2(1), 26-50. 

Hickson, D., Boivin, A., Daly, M.G., Ghent R., Nolan, M.C., Tait, K., Cunje, A., and Tsai, C-A. (2018) Near surface bulk density estimates of NEAs from radar observations and permittivity measurements of powdered geologic material. Icarus, 306, 16-24. 

Boivin, A., Hickson, D., Cunje, A., Tsai, C-A., Ghent, R.R., and Daly, M. (2018) Broadband Measurements of the Complex Permittivity of Planetary Regolith Analog Materials. Journal of Geophyisical Research: Planets, 123, 3088-3104. 

Osinski, G.R., et. al (including Hickson, D.) (2018) The CanMars Mars Sample Return analogue mission. Planetary and Space Science, 166, 110-130. 

Hickson, D., Sotodeh, S., Daly, M., Ghent, R., and Nolan, M.C. (2017) Improvements on effective permittivity measurements of powdered alumina: Implications for bulk permittivity properties of asteroid regoliths. Advances in Space Research, 59, 472-482. 

Non-Peer-Reviewed Publications

Anish Roshi, D., et al (including Hickson, D.) (2019) Astro2020 Activities and Projects White Paper: Arecibo Observatory in the Next Decade. Submitted as an Activities and Projects White Paper for the Astro2020 decadal survey. 

Carter, T., Contreras, D., Doyle, S., Hickson, D., Mihailovic, D., Morgan, J., and Moutsiou, T. (2014) Stelida Naxos Archaeological Project - 2014 Report. Submitted to the Canadian Institute in Greece. 

Select First-Author Conference Abstracts

Hickson, D.C., Becker, T.M., Virkki, A.K., Venditti, F.C.F., Marshall, S.E., Zambrano-Marin, L.F., and McGilvray, A. (2020) Space Weathering Effects from UV to Radar Wavelengths (poster [1704]). 51st Lunar and Planetary Science Conference (LPSC), conference cancelled due to COVID-19. 

Hickson, D.C., Boivin, A.L., Tsai, C., Daly, M.G., Ghent, R.R. (2019) Quantifying Asteroid Regolith Porosity from Radar Data (poster [2480]). 50th LPSC, The Woodlands, USA, 18-22 Mar. 

Hickson, D.C., Boivin, A., Daly, M.G., Ghent, R.R., C. Tsai, Tait, K. (2018) Measurement-based Modeling of the Dielectric Permittivity of Particulate Geologic Material for Improved Radar Interpretation (poster [P51G-2964]). 2018 American Geophysical Union (AGU) Fall Meeting, Washington DC, USA, 10-14 Dec. 

Hickson, D.C., Boivin, A., Daly, M.G., Ghent, R.R., Tait, K. (2018) Characterizing the Dielectric Behaviour of Asteroid Regolith Analogue Minerals for Planetary Radar Interpretation (poster). Women in Planetary Science and Exploration (WPSE) 2018, Toronto, Canada, 17-18 Feb. 

Hickson, D., Boivin, A., Daly, M.G., Ghent, R.R., Nolan, M.C., Tait, K., Cunje, A., Tsai, C-A. (2017) Constraining Bulk Densities of Near-Earth Asteroid Surfaces from Radar Observations Using Laboratory Measurements of Permittivity (poster) [P13B-2555]. 2017 AGU Fall Meeting, New Orleans, USA, 11-15 Dec. 

";
$orcid_link = "https://orcid.org/0000-0002-0158-9537";

$stmt->execute();
if(!$stmt->execute()){
  echo "Error #". $conn->errno . " \n";
  echo $conn->error;
} else{
  echo "Success!";

}
$stmt->close();

 // Query to Select all publications

// Query to Select all publications


$sql = "SELECT * FROM $table ORDER BY ID"; // Query to Select all publications
$mysqli = $conn->query($sql); // Execute Query

if (isset($mysqli)) {
    
    while ($row = $mysqli -> fetch_row()) {
      printf ("%s (%s)\n", $row[0], $row[12]);
      echo "Ran";
    } 
    $mysqli -> free_result();
  }else{
    echo "Failed";
}


$conn->close(); 
?>