<?php
////////////////////////////////////////////////////
/**
* The following PHP scripts displays all data of a staff member
*
* Code generated by Yjang Wynter (Web Developer)
* Florida Space Institute (Remote)
* University of Central Florida
*
* @author     Yjang Wynter <yjang.wynter@ucf.edu>
* @version    0.1
* 
*/
///////////////////////////////////////////////////////
$servername = "localhost"; // DB Server Host
$username  = "root"; //DB User
$password  = ""; // DB Password
$database  =  "fsi"; //Database name
$table = "science_staff";
$conn = new mysqli($servername, $username, $password,$database); // SQL Database Connector
//PDO

if (!$conn) {
  die('No pudo conectarse: ' . $conn->error($e)); // Failed to Connect
  }
  
  $sql = "INSERT INTO $table (FULL_NAME, PHONE_EXT, PRIMARY_MAIL, ALT_MAIL, POSITION, DEPARTMENT,  BIOGRAPHY, PROJECTS, RESEARCH_AREAS, RESEARCH_DESCRIPTION, MENTORING, PUBLICATIONS, ORCID_LINK) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
  $stmt =$conn->prepare($sql);
  $stmt ->bind_param("sssssssssssss",$name,$phone,$p_mail,$alt_mail,$pos,$dept, $bio,$projects,$res_areas,$res_desc, $mentoring,$pubs,$orcid_link);
  
//Test
$name ="Anna Mcgilvray";
$phone ="254";
$p_mail ="an801855@ucf.edu";
$alt_mail="";
$pos = "Science Operations Associate";
$dept ="Planetary Sciences";
$bio = "
Anna was born and raised in Texas, staying there until she graduated in 2018 from the University of Texas at Austin with bachelor's degrees in astronomy and physics. As an undergraduate she worked with Dr. Kristen McQuinn to study starburst phenomena in nearby dwarf galaxies. Since graduating, she lived for a year in California, where she spent most of her free time hiking in the Sierra Nevadas. She moved to Puerto Rico and started working at the Arecibo Observatory in December of 2019, as a science operations associate with both the Planetary Sciences and the Astronomy departments. 
";
$res_areas ="
open ended
";
$res_desc ="
*Note that I am also in the Astronomy Department. 
As someone who recently graduated from undergrad, I am interested in learning more about pretty much everything, which has been a boon as my job has me working on many different areas of research! 
";
$projects= "
Anna is partially funded by a four year NASA NEO grant awarded to Arecibo Observatory in 2019.  
";
$mentoring ="";
$pubs = "";
$orcid_link = "";


 // Query to Select all publications

// Query to Select all publications


$sql = "SELECT * FROM $table ORDER BY ID"; // Query to Select all publications
$mysqli = $conn->query($sql); // Execute Query

if (isset($mysqli)) {
    
    while ($row = $mysqli -> fetch_row()) {
      printf ("%s (%s)\n", $row[0], $row[12]);
      echo "Ran";
    } 
    $mysqli -> free_result();
  }else{
    echo "Failed";
}


$conn->close(); 
?>