<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Staff Page Example </title>
    <link rel="stylesheet" href="./css/staff.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
</head>

<body>
    <div class="container-fluid">
<?php
session_start();
////////////////////////////////////////////////////
/**
* The following PHP scripts displays all data of a staff member
*
* Code generated by Yjang Wynter (Web Developer)
* Florida Space Institute (Remote)
* University of Central Florida
*
* @author     Yjang Wynter <yjang.wynter@ucf.edu>
* @version    0.1
* 
*/
///////////////////////////////////////////////////////

$servername = "localhost"; // DB Server Host
$username  = "root"; //DB User
$password  = ""; // DB Password
$database  =  "fsi"; //Database name
$table = "science_staff";
$conn = new mysqli($servername, $username, $password,$database); // SQL Database Connector
//PDO
if (!$conn) {
    die('No pudo conectarse: ' . $conn->error($e)); // Failed to Connect
    }

    
    $sql = "SELECT FULL_NAME, POSITION, DEPARTMENT, PRIMARY_MAIL, PHONE_EXT FROM $table ORDER BY FULL_NAME";
    $result =  $conn->query($sql);
    if(!$result > 0){
      echo "Error #". $conn->errno . " \n";
      echo $conn->error;
    } else{
        //CREATE SESSION VARIABLE
      

        $count = 0; //create a counter 
        ?>                <div class="row col-sm-12 mx-auto my-auto">
        <?php
        while($row = $result->fetch_assoc()){

             if (($count +1) % 4 ==0){ //Prints the new row and a card for every four entries
               //Closes the previous row ?> </div>
                <div class="row col-sm-12 mx-auto my-auto">
                    <div class="card col-sm-3 my-2 px-0 mx-2 px-0 ">
                        <div class=" card-header py-0 px-0">
                        <!-- Not sure how to implement this
                        But the idea is click the image to get the name of the entry from the sibling node below.
                         then set that name to a session variable to then use to query the information of the staff member and their
                        information in the next page. --><a onclick="getProfile();" href="./staff.php"><img class="img-fluid card-img-top"src="./img/astro_profile.png" width="50%"></a>
                        </div>
                        <div  class="card-body bg-dark text-light">
                            <p class="card-title m-0 p-0 text-center"> <?php echo $row['FULL_NAME']; ?> </p>
                        </div>
                        <div class="card-footer bg-secondary  d-flex justify-content-center align-items-center text-light">
                        
                            <ul style="list-style-type:none;"class="col-sm-12 mx-0 px-0">
                                <li class="text-sm-left mx-3 row">
                                <span><i class="fas fa-user mx-4"></i></span>     <?php echo $row['POSITION']; ?>    
                                </li>
                                <li class="text-sm-left mx-3 row">
                                <span><i class="fas fa-building mx-4"></i></span>     <?php echo $row['DEPARTMENT']; ?>
                                </li>
                                <li class="text-sm-left mx-3 row">
                                <span><i class="fas fa-envelope mx-4"></i></span>    <?php echo $row['PRIMARY_MAIL']; ?>
                                </li>
                                <li class="text-sm-left mx-3 row">
                                <span><i class="fas fa-phone-alt mx-4"></i></span>Ext:    <?php echo $row['PHONE_EXT']; ?>
                                </li>
                            </ul>
                        </div>
                    </div>
                
                <?php
            } else if (($count +1) % 4 !=0 ){  // prints the cards in the row 
                //Prints the first row
                //if the four or more entries exist, end the last row and create new row
                ?><div class="card col-sm-3 my-2 px-0 mx-2 px-0 ">

                <div class=" card-header py-0 px-0">
                <a onclick="getProfile();" href="./staff.php"><img class="img-fluid card-img-top"src="./img/astro_profile.png" width="50%"></a>
                </div>
                <div class="card-body bg-dark text-light">
                    <p class="card-title m-0 p-0 text-center"> <?php echo $row['FULL_NAME']; ?> </p>
                </div>
                <div class="card-footer bg-secondary  d-flex justify-content-center align-items-center text-light">
                
                    <ul style="list-style-type:none;"class="col-sm-12 mx-0 px-0">
                        <li class="text-sm-left mx-3 row">
                        <span><i class="fas fa-user mx-4"></i></span>     <?php echo $row['POSITION']; //the position of the staff?>    
                        </li>
                        <li class="text-sm-left mx-3 row">
                        <span><i class="fas fa-building mx-4"></i></span>     <?php echo $row['DEPARTMENT'];//the department of the staff ?>
                        </li>
                        <li class="text-sm-left mx-3 row">
                        <span><i class="fas fa-envelope mx-4"></i></span>    <?php echo "<a class='text-light' href='mailto:".$row['PRIMARY_MAIL']."'>".$row['PRIMARY_MAIL']."</a>"; // the email link of the staff?>
                        </li>
                        <li class="text-sm-left mx-3 row">
                        <span><i class="fas fa-phone-alt mx-4"></i></span>Ext:    <?php echo $row['PHONE_EXT']; //Phone extension of the staff ?>
                        </li>
                    </ul>
                </div>
            </div> <?php 

            } 
            $count++; // counter adds to itself to loop through the next row
        }
    }
     
    $conn->close();
   
?>





     
        
    </div>
    <script src="./js/staff.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
    
</body>

</html>