<?php
////////////////////////////////////////////////////
/**
* The following PHP scripts displays all White papers requesting use of the Arecibo Telescope
*
* Code generated by Jorge L. Herrera (Software Engineer)
* Computer Department
* Arecibo Observatory
*
* @author     Jorge L. Herrera <jherrera@naic.edu>
* @version    1.0
* @link       http://www.naic.edu/pkg/webutils/astro/astro2020.php
*/
///////////////////////////////////////////////////////
$servername = "<server here>"; // DB Server Host
$username   = "<user here>"; //DB User
$password   = "<password here>"; // DB Password
$database   = "Astro_Publications"; //Database name
date_default_timezone_set("America/Puerto_Rico"); // Set default timezone
$current_datetime = date('Y-m-d H:i:s'); // Current datetime
// Create connection
$conn = mysqli_connect($servername, $username, $password); // SQL Database Connector
if (!$conn) {
die('No pudo conectarse: ' . mysqli_error($e)); // Failed to Connect
}
mysqli_select_db($database, $conn); //Select database
$pubs_query = "SELECT * from `WhitePapers`"; // Query to Select all publications
$results    = mysqli_query($pubs_query, $conn); // Execute Query
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="https://outreach.naic.edu/ao/misc/favicon.ico">
    <title>White Papers - Astro 2020
    </title>
    <!-- Bootstrap Core CSS -->
    <link href="http://www.naic.edu/pkg/webutils/astro/assets/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Menu CSS -->
    <link href="http://www.naic.edu/pkg/webutils/astro/assets/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">
    <link href="http://www.naic.edu/pkg/webutils/astro/assets/bower_components/datatables/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
    <!-- Custom CSS -->
    <link href="http://www.naic.edu/pkg/webutils/astro/css/style.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
  </head>
  <body>
    <!-- row -->
    <div class="row">
      <div class="col-sm-10">
        <div class="white-box">
          <table>
            <tr>
              <td valign="top">
                <h3>Astro 2020
                </h3>
              </td>
              <td>
                <br.
                     <p class="text-muted m-b-30">: White papers requesting use of the Arecibo Telescope
            </p>
            </td>
          </tr>
        </table>
      <table id="myTable" class="table table-striped">
        <thead>
          <tr>
            <th>PI:
              <br>Last Name
            </th>
            <th width="40">PI: First Name
            </th>
            <th>PI: Institution
            </th>
            <th>Title
            </th>
            <th>Description
            </th>
          </tr>
        </thead>
        <tbody>
          <?php
while ($rows = mysqli_fetch_array($results)) {
$submitted   = $rows["date_submitted"];
$first       = $rows["pi_firstname"];
$last        = $rows["pi_lastname"];
$institution = $rows["pi_institution"];
$title       = $rows["white_paper_title"];
$description = $rows["white_paper_description"];
$link        = $rows["link"];
?>
          <tr >
            <td>
              <font color="#606060">
                <?php
echo $last;
?>
              </font>
            </td>
            <td>
              <font color="606060">
                <?php
echo $first;
?>
              </font>
            </td>
            <td >
              <font color="606060">
                <?php
echo $institution;
?>
              </font>
            </td>
            <td>
              <a href="<?php
                       echo $link;
                       ?>" target="_blank">
                <?php
echo $title;
?>
              </a>
            </td>
            <td >
              <font color="606060">
                <?php
echo $description;
?>
              </font>
            </td>
            <?php
}
?>
        </tbody>
      </table>
    </div>
    </div>
  </div>
<!-- /.row -->
<!-- /#wrapper -->
<!-- jQuery -->
<script src="http://www.naic.edu/pkg/webutils/astro/assets/bower_components/jquery/dist/jquery.min.js">
</script>
<!-- Bootstrap Core JavaScript -->
<script src="http://www.naic.edu/pkg/webutils/astro/assets/bower_components/bootstrap/dist/js/bootstrap.min.js">
</script>
<!-- Menu Plugin JavaScript -->
<script src="http://www.naic.edu/pkg/webutils/astro/assets/bower_components/metisMenu/dist/metisMenu.min.js">
</script>
<!--Nice scroll JavaScript -->
<script src="http://www.naic.edu/pkg/webutils/astro/js/jquery.nicescroll.js">
</script>
<script src="http://www.naic.edu/pkg/webutils/astro/assets/bower_components/datatables/jquery.dataTables.min.js">
</script>
<script>
  $(document).ready(function() {
    $('#myTable').DataTable();
    $(document).ready(function() {
      var table = $('#example').DataTable({
        "columnDefs": [{
          "visible": false,
          "targets": 2
        }
                      ],
        "order": [
          [2, 'asc']
        ],
        "displayLength": 25,
        "drawCallback": function(settings) {
          var api = this.api();
          var rows = api.rows({
            page: 'current'
          }
                             ).nodes();
          var last = null;
          api.column(2, {
            page: 'current'
          }
                    ).data().each(function(group, i) {
            if (last !== group) {
              $(rows).eq(i).before(
                '<tr class="group"><td colspan="5">' + group + '</td></tr>'
              );
              last = group;
            }
          }
                                 );
        }
      }
                                         );
      // Order by the grouping
      $('#example tbody').on('click', 'tr.group', function() {
        var currentOrder = table.order()[0];
        if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
          table.order([2, 'desc']).draw();
        }
        else {
          table.order([2, 'asc']).draw();
        }
      }
                            );
    }
                     );
  }
                   );
</script>
<!--Wave Effects -->
<script src="http://www.naic.edu/pkg/webutils/astro/js/waves.js">
</script>
<!-- Custom Theme JavaScript -->
</body>
</html>
